"""add_network_analysis

Revision ID: 436dae8b7dd3
Revises: 483d5795ed63
Create Date: 2026-09-03 00:28:45.474333
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '436dae8b7dd3'
down_revision: Union[str, None] = '483d5795ed63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('weak_component_count', sa.Integer(), nullable=False),
    sa.Column('strong_component_count', sa.Integer(), nullable=False),
    sa.Column('largest_weak_component_size', sa.Integer(), nullable=False),
    sa.Column('connected_user_count', sa.Integer(), nullable=False),
    sa.Column('isolated_user_count', sa.Integer(), nullable=False),
    sa.Column('algorithm_params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_analysis_runs_topic_id'), 'network_analysis_runs', ['topic_id'], unique=False)
    op.create_table('community_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_community_id', sa.Integer(), nullable=False),
    sa.Column('target_community_id', sa.Integer(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['network_analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'source_community_id', 'target_community_id', name='uq_community_flows_run_source_target')
    )
    op.create_index(op.f('ix_community_flows_run_id'), 'community_flows', ['run_id'], unique=False)
    op.create_index(op.f('ix_community_flows_source_community_id'), 'community_flows', ['source_community_id'], unique=False)
    op.create_index(op.f('ix_community_flows_target_community_id'), 'community_flows', ['target_community_id'], unique=False)
    op.create_table('network_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['network_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'source_user_id', 'target_user_id', name='uq_network_edges_run_source_target')
    )
    op.create_index(op.f('ix_network_edges_run_id'), 'network_edges', ['run_id'], unique=False)
    op.create_index(op.f('ix_network_edges_source_user_id'), 'network_edges', ['source_user_id'], unique=False)
    op.create_index(op.f('ix_network_edges_target_user_id'), 'network_edges', ['target_user_id'], unique=False)
    op.create_table('network_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pagerank_score', sa.Float(), nullable=False),
    sa.Column('in_degree', sa.Integer(), nullable=False),
    sa.Column('out_degree', sa.Integer(), nullable=False),
    sa.Column('weighted_in_degree', sa.Float(), nullable=False),
    sa.Column('weighted_out_degree', sa.Float(), nullable=False),
    sa.Column('betweenness_centrality', sa.Float(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('cross_community_edge_count', sa.Integer(), nullable=False),
    sa.Column('communities_reached', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['network_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'user_id', name='uq_network_nodes_run_user')
    )
    op.create_index(op.f('ix_network_nodes_community_id'), 'network_nodes', ['community_id'], unique=False)
    op.create_index(op.f('ix_network_nodes_run_id'), 'network_nodes', ['run_id'], unique=False)
    op.create_index(op.f('ix_network_nodes_user_id'), 'network_nodes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_nodes_user_id'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_run_id'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_community_id'), table_name='network_nodes')
    op.drop_table('network_nodes')
    op.drop_index(op.f('ix_network_edges_target_user_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_source_user_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_run_id'), table_name='network_edges')
    op.drop_table('network_edges')
    op.drop_index(op.f('ix_community_flows_target_community_id'), table_name='community_flows')
    op.drop_index(op.f('ix_community_flows_source_community_id'), table_name='community_flows')
    op.drop_index(op.f('ix_community_flows_run_id'), table_name='community_flows')
    op.drop_table('community_flows')
    op.drop_index(op.f('ix_network_analysis_runs_topic_id'), table_name='network_analysis_runs')
    op.drop_table('network_analysis_runs')
    # ### end Alembic commands ###
