"""add_collection_provenance

Revision ID: 483d5795ed63
Revises: 8290f8d16993
Create Date: 2026-09-03 00:06:01.598484
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '483d5795ed63'
down_revision: Union[str, None] = '8290f8d16993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_key', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_queries_category'), 'collection_queries', ['category'], unique=False)
    op.create_index(op.f('ix_collection_queries_query_key'), 'collection_queries', ['query_key'], unique=True)
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('effective_query_text', sa.String(length=500), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('retrieved_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['collection_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_query_id'), 'collection_runs', ['query_id'], unique=False)
    op.create_table('tweet_collection_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('collection_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id', 'collection_run_id', name='uq_tweet_collection_sources_tweet_run')
    )
    op.create_index(op.f('ix_tweet_collection_sources_collection_run_id'), 'tweet_collection_sources', ['collection_run_id'], unique=False)
    op.create_index(op.f('ix_tweet_collection_sources_tweet_id'), 'tweet_collection_sources', ['tweet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_collection_sources_tweet_id'), table_name='tweet_collection_sources')
    op.drop_index(op.f('ix_tweet_collection_sources_collection_run_id'), table_name='tweet_collection_sources')
    op.drop_table('tweet_collection_sources')
    op.drop_index(op.f('ix_collection_runs_query_id'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_collection_queries_query_key'), table_name='collection_queries')
    op.drop_index(op.f('ix_collection_queries_category'), table_name='collection_queries')
    op.drop_table('collection_queries')
    # ### end Alembic commands ###
