"""add_topics_and_trends

Revision ID: 8290f8d16993
Revises: 97d23df46fa0
Create Date: 2026-09-02 23:20:41.892170
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8290f8d16993'
down_revision: Union[str, None] = '97d23df46fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('dataset_tweet_count', sa.Integer(), nullable=False),
    sa.Column('earliest_tweet_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_tweet_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('embedding_model_id', sa.String(length=255), nullable=True),
    sa.Column('embedding_model_revision', sa.String(length=64), nullable=True),
    sa.Column('clustering_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_analysis_runs_pipeline_version'), 'trend_analysis_runs', ['pipeline_version'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('representative_terms', sa.JSON(), nullable=False),
    sa.Column('topic_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['trend_analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_run_id'), 'topics', ['run_id'], unique=False)
    op.create_index(op.f('ix_topics_topic_type'), 'topics', ['topic_type'], unique=False)
    op.create_table('trend_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('baseline_mentions', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['trend_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'topic_id', 'window_start', 'window_end', name='uq_trend_windows_run_topic_window')
    )
    op.create_index(op.f('ix_trend_windows_run_id'), 'trend_windows', ['run_id'], unique=False)
    op.create_index(op.f('ix_trend_windows_topic_id'), 'trend_windows', ['topic_id'], unique=False)
    op.create_index(op.f('ix_trend_windows_window_end'), 'trend_windows', ['window_end'], unique=False)
    op.create_index(op.f('ix_trend_windows_window_start'), 'trend_windows', ['window_start'], unique=False)
    op.create_table('tweet_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('membership_probability', sa.Float(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['trend_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'tweet_id', 'topic_id', name='uq_tweet_topics_run_tweet_topic')
    )
    op.create_index(op.f('ix_tweet_topics_run_id'), 'tweet_topics', ['run_id'], unique=False)
    op.create_index(op.f('ix_tweet_topics_topic_id'), 'tweet_topics', ['topic_id'], unique=False)
    op.create_index(op.f('ix_tweet_topics_tweet_id'), 'tweet_topics', ['tweet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_topics_tweet_id'), table_name='tweet_topics')
    op.drop_index(op.f('ix_tweet_topics_topic_id'), table_name='tweet_topics')
    op.drop_index(op.f('ix_tweet_topics_run_id'), table_name='tweet_topics')
    op.drop_table('tweet_topics')
    op.drop_index(op.f('ix_trend_windows_window_start'), table_name='trend_windows')
    op.drop_index(op.f('ix_trend_windows_window_end'), table_name='trend_windows')
    op.drop_index(op.f('ix_trend_windows_topic_id'), table_name='trend_windows')
    op.drop_index(op.f('ix_trend_windows_run_id'), table_name='trend_windows')
    op.drop_table('trend_windows')
    op.drop_index(op.f('ix_topics_topic_type'), table_name='topics')
    op.drop_index(op.f('ix_topics_run_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_trend_analysis_runs_pipeline_version'), table_name='trend_analysis_runs')
    op.drop_table('trend_analysis_runs')
    # ### end Alembic commands ###
