"""add_sarcasm_provenance

Revision ID: 97d23df46fa0
Revises: 13f1ff29741b
Create Date: 2026-09-02 15:09:28.364391
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97d23df46fa0'
down_revision: Union[str, None] = '13f1ff29741b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_results', sa.Column('sarcasm_model_id', sa.String(length=255), nullable=True))
    op.add_column('sentiment_results', sa.Column('sarcasm_model_revision', sa.String(length=64), nullable=True))
    op.add_column('sentiment_results', sa.Column('sarcasm_pipeline_version', sa.String(length=64), nullable=True))
    op.add_column('sentiment_results', sa.Column('fusion_status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiment_results', 'fusion_status')
    op.drop_column('sentiment_results', 'sarcasm_pipeline_version')
    op.drop_column('sentiment_results', 'sarcasm_model_revision')
    op.drop_column('sentiment_results', 'sarcasm_model_id')
    # ### end Alembic commands ###
